name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    env:
      IMAGE_URL: ${{ secrets.SCALEWAY_REGION_URL }}/${{ secrets.SCALEWAY_NAMESPACE }}/ballejaune:latest
      S3_PROVIDER: scw-fr-par
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: docker/login-action@v3
        name: Login to registry
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_REGISTRY_PASSWORD }}
          registry: ${{ secrets.SCALEWAY_REGION_URL }}/${{ secrets.SCALEWAY_NAMESPACE }}
      - name: Pull last image
        run: docker pull $IMAGE_URL || true
      - name: Build new image
        run: docker build --cache-from $IMAGE_URL --tag $IMAGE_URL .
      - name: Push new image
        run: docker push $IMAGE_URL